finished task 3
agfonte/weather pull request #6
Opened 2022-06-30 04:44 UTC by licuevas98

task#3: maked the browser to get current weather conditions for the location of the user

2022-07-02 15:41 UTC, agfonte commented
.idea folder should not be included in commit, please remove it

2022-07-02 15:52 UTC, agfonte requested changes
General guidelines:
- Never attack sensitive data into the code
- Try following design patterns like MVC, please separate the logic from the view from the model
- Do not add into the codebase unnecessary folders/files like .idea or others

2022-07-02 15:52 UTC, agfonte commented on src/components/NavPage.js
> +    const key = "NQ6gDQ8Tb5v7rkrFyUH7yUunW5R2VRWh";
Never put sensitive data into a commit, please move this to an env variable

2022-07-02 15:52 UTC, agfonte commented on src/components/NavPage.js
> +        //res.push(data[0].WeatherText);
remove commented code please

2022-07-02 15:52 UTC, agfonte commented on src/components/NavPage.js
> +    const gettingWeather = () => {
This methods should not be on the NavPage, please move it to a different file that will be in charge of doing all the logic of getting data from the API and then use those methods please

2022-07-03 00:42 UTC, licuevas98 reviewed
task#3: implemented feedback in the project

2022-07-03 17:33 UTC, agfonte requested changes
The apikey should not be an input of the user, should be read from the environment (as an environment variable) or any other secure mechanism for sensitive data.

Please remove the input for the apikey for the user and use this type of mechanism

2022-07-03 17:33 UTC, agfonte commented on src/App.js
>      // const routing = useRoutes(routes);
Commented code, please remove it

2022-07-04 08:30 UTC, agfonte approved these changes
Great job!

2022-07-04 08:30 UTC, merged